#include <Arduino.h>

String trivia_answers_explained[] = {
    "", 
    "You can't sneeze when you're asleep!", 
    "",
    "Herbivores consume plants!",
    "", "", 
    "The capital of France is Paris!", 
    "There are only two lungs in the human body!", 
    "There are 206 bones in the human body!",
    "Jupiter is the largest planet in our solar system!", 
    "", 
    "An atom is the smallest unit of matter!", 
    "", "", 
    "Jellyfish do not have brains!",    
    "",
    "Pluto is not a planet, it is a dwarf planet!", 
    "",
    "Sharks have rough skin that feels like sandpaper!",
    "", "",
    "The Nile is the longest river in the world!",
    "Blue whales are the largest animals on Earth!", 
    "Sharks are fish!",
    "The closest planet to the sun is Mercury!",
    "Russia is the largest country in the world!", 
    "", "", "", "",
    "Omnivores eat both plants and animals!", 
    "", "", "", "", "", 
    "They are called syllables!", 
    "", "", "",
    "There are seven days in a week!",
    "A triangle only has three, a pentagon has five!",
    "", "", "", "", "", "", "", "",
    "They have eight legs!",
    "", "", "",
    "It is the hardest natural substance in the world!",
    "", "",
    "The Statue of Liberty is in New York!",
    "The German shepherd is a breed of dog!",
    "Spring is before summer, fall is after summer!",
    "There are 24 hours in a day!",
    "", "",
    "Male seahorses get pregnant!",
    "","","",
    }; 

String trivia_questions[] = {
    "  Camels have three\n  sets of eyelids.", 
    "  It is possible to\n  sneeze while\n  sleeping.", 
    "  Australia is a\n  country as well as\n  a continent.", 
    "  Herbivore animals\n  consume meat.", 
    "  Pneumonia is an\n  infection that\n  affects lungs.", 
    "  The capital of\n  Spain is Madrid.", 
    "  The capital of\n  France is\n  Washington DC.", 
    "  There are four\n  lungs found in\n  the human body.",
    "  The human body\n  consists of\n  150 bones.",
    "  Jupiter is the\n  smallest planet in\n  the solar system.", 
    "  Mt. Everest is\n  the highest\n  mountain in the\n  world.", 
    "  A molecule is the\n  smallest unit\n  of matter.", 
    "  The Sahara desert\n  is the biggest\n  desert in the\n  world.", 
    "  A century\n  consists of one\n  hundred years.", 
    "  Jellyfish have\n  brains.",
    "  You can't make\n  red, yellow, and blue\n  paint by mixing\n  other colors.",
    "  Even though Pluto\n  is small, it is\n  still called a\n  planet.", 
    "  An octopus has\n  three hearts.",
    "  Sharks have\n  smooth skin.",
    "  Chlorophyll is\n  responsible for\n  green color in\n  plants.",
    "  The Nile is not\n  the longest river in\n  the world.",
    "  Elephants are the\n  largest animals in\n  the world.", 
    "  Sharks are\n  mammals.",
    "  The closest planet\n  to the sun\n  is Venus.",
    "  China is the\n  largest country\n  in the world. ", 
    "  Asia is the\n  largest continent\n  in the world.",
    "  The human heart\n  is about the\n  size of a fist.", 
    "  There are seven\n  colors in the\n  rainbow.",
    "  A falcon is the\n  fastest animal in\n  the world.",
    "  Omnivores eat\n  only plants.", 
    "  The largest bone\n  in the human\n  body is the\n  thigh bone. ",
    "  A sloth takes two\n  weeks to digest\n  food.", 
    "  A group of\n  jellyfish is called a\n  smack.",
    "  The horn of\n  rhinoceros is\n  made of hair.",
    "  Adult humans have\n  32 teeth.", 
    "  A, I, E, O, U in\n  the alphabet are\n  called consonants.",
    "  There are 365\n  days in a year.",
    "  We can see a full\n  moon every 29\n  days.",
    "  Chameleons can\n  change the color\n  of their body. ",
    "  There are eight\n  days in a week.",
    "  There are five\n  sides in a\n  triangle.",
    "  The offspring of\n  a frog is called\n  a tadpole.",
    "  The largest animal\n  in the world is\n  the blue whale.",
    "  Skin is the\n  largest organ in\n  the human body.",
    "  There are 7\n  continents in the\n  world. ",
    "  The sun rises\n  from the East and\n  sets in the West.",
    "  Clouds are made\n  out of water.",
    "  Cheetah is the\n  fastest animal on\n  land in the\n  world.",
    "  There are 8\n  planets in the\n  solar system.",
    "  Spiders have five\n  legs.",
    "  Things fall when\n  you drop them\n  because of\n  gravity.",
    "  Lava is the molten\n  rock from volcanic\n  eruptions. ",
    "  Comets are made of\n  ice and rock.",
    "  Diamond is the\n  softest natural\n  substance in the\n  world. ",
    "  The Titanic sank\n  in 1912.",
    "  Chihuahuas are the\n  smallest breed of\n  dog.",
    "  The Statue of\n  Liberty is\n  located in Texas.",
    "  The German\n  shepherd is a breed\n  of cat. ",
    "  The onset of\n  spring season is\n  after summer. ",
    "  There are 18\n  hours in a day.",
    "  Equator is the\n  line that passes\n  through the middle\n  of the earth. ",
    "  Ears and noses\n  continue to grow\n  throughout life.",
    "  Female seahorses\n  get pregnant.",
    "  Snakes smell with\n  their tongue.",
    "  Humans are 70%\n  water. ",
    "  Hummingbirds can\n  fly backwards.",
    "  Crocodiles shed\n  tears when they\n  eat food."
    }; 

String trivia_answers[] = {
    "True", 
    "False", 
    "True",
    "False",
    "True",
    "True", 
    "False", 
    "False", 
    "False",
    "False", 
    "True", 
    "False", 
    "True", 
    "True", 
    "False",    
    "True",
    "False", 
    "True",
    "False",
    "True", 
    "False",
    "False", 
    "False",
    "False",
    "False", 
    "True",
    "True", 
    "True",
    "True",
    "False", 
    "True",
    "True", 
    "True",
    "True",
    "True", 
    "False",
    "True",
    "True",
    "True",
    "False",
    "False",
    "True",
    "True",
    "True",
    "True",
    "True",
    "True",
    "True",
    "True",
    "False",
    "True",
    "True",
    "True",
    "False",
    "True",
    "True",
    "False",
    "False",
    "False",
    "False",
    "True",
    "True",
    "False",
    "True",
    "True",
    "True",
    "True"
    }; 